version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deployment:
    production:
      branch: master
        commands:
          - git remote add production dokku@$DOKKU_SERVER_ADDRESS:api
          - git push production master
workflows:
    build-and-test:
      jobs:
        - build-and-test