version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: git remote add dokku dokku@$DOKKU_SERVER_ADDRESS:api
      - run: ssh-keyscan -H $DOKKU_SERVER_ADDRESS >> ~/.ssh/known_hosts
      - run: git push -q -f dokku $CIRCLE_BRANCH:master

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /master|dev/
  deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: /master|dev/
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: /master|dev/